theme: jekyll-theme-minimal
title: Welcome to the homepage!
description: This will be updated soon, please visit again in the future!
show_downloads: true
logo: https://cdn.pixabay.com/photo/2013/05/29/22/25/elephant-114543__340.jpg
